######################################################################
# Automatically generated by qmake (3.0) Sa Jul 16 12:14:34 2016
######################################################################

TEMPLATE = app
TARGET = thread
INCLUDEPATH += .

# Input
SOURCES += thread.cpp

CONFIG += console
