all:
	$(MAKE) -C k1
	$(MAKE) -C k1/einausgabe
	$(MAKE) -C k24
	$(MAKE) -C k12
	$(MAKE) -C k8/mathvek
	$(MAKE) -C k8/vektor
	$(MAKE) -C k8/matrix
	$(MAKE) -C k8/funktor
	$(MAKE) -C k8/zuweisung_vergleich
	$(MAKE) -C k8/literale
	$(MAKE) -C k8/new/waechter
	$(MAKE) -C k8/new/eigene
	$(MAKE) -C k8/new/zaehlend
	$(MAKE) -C k8/new/new
	$(MAKE) -C k8/smartptr
	$(MAKE) -C k8/datum
	$(MAKE) -C k8/rational
	$(MAKE) -C k7
	$(MAKE) -C k7/logik
	$(MAKE) -C k7/speicher
	$(MAKE) -C k7/stream
	$(MAKE) -C k32
	$(MAKE) -C k27
	$(MAKE) -C k27/array
	$(MAKE) -C k27/vector
	$(MAKE) -C k27/list
	$(MAKE) -C k19
	$(MAKE) -C k19/dynLib/anwendung
	$(MAKE) -C k19/dynLib/libprojekt
	$(MAKE) -C k19/abhaengigkeiten
	$(MAKE) -C k19/verzTrennung
	$(MAKE) -C k19/templateInst/inklusion
	$(MAKE) -C k19/templateInst/extern
	$(MAKE) -C k19/staticLib/anwendung
	$(MAKE) -C k19/staticLib/libprojekt
	$(MAKE) -C k19/dirTreeRec
	$(MAKE) -C k19/dirTree
	$(MAKE) -C k14
	$(MAKE) -C k14/RegexTester
	$(MAKE) -C k11/tauschen
	$(MAKE) -C k11/plus
	$(MAKE) -C k11/RVO
	$(MAKE) -C k11/move
	$(MAKE) -C k11/move/unique_ptr
	$(MAKE) -C k2
	$(MAKE) -C k2/inline
	$(MAKE) -C k20
	$(MAKE) -C k20/tdd
	$(MAKE) -C k20/datum
	$(MAKE) -C k21
	$(MAKE) -C k13/rekursiveTemplates
	$(MAKE) -C k13/variadicTemplate
	$(MAKE) -C k33
	$(MAKE) -C k22/bidirektionaleAssoziation
	$(MAKE) -C k22/interface
	$(MAKE) -C k15
	$(MAKE) -C k15/prodcons
	$(MAKE) -C k15/rw
	$(MAKE) -C k5/decltype
	$(MAKE) -C k5/klasseMitKonstanten
	$(MAKE) -C k5/meinstring
	$(MAKE) -C k5/numobj
	$(MAKE) -C k5/numobjinline
	$(MAKE) -C k5/stack
	$(MAKE) -C k5/stringansicht
	$(MAKE) -C k23/strings
	$(MAKE) -C k23/strings/zahl2string
	$(MAKE) -C k23/strings/string2zahl
	$(MAKE) -C k23/array2dmath
	$(MAKE) -C k23/array2dmath/performancetest
	$(MAKE) -C k23/array2dmath/performancetest/boost
	$(MAKE) -C k23/array2dmath/performancetest/array2d
	$(MAKE) -C k23/sortieren
	$(MAKE) -C k23/finden
	$(MAKE) -C k23/complex
	$(MAKE) -C k23/vermischtes
	$(MAKE) -C k23/vermischtes/regex
	$(MAKE) -C k23/vermischtes/copy
	$(MAKE) -C k23/zufallszahlen
	$(MAKE) -C k23/vergleich
	$(MAKE) -C k23/mengen
	$(MAKE) -C k23/textverarbeitung
	$(MAKE) -C k23/textverarbeitung/regex
	$(MAKE) -C k23/folgen
	$(MAKE) -C k23/heap
	$(MAKE) -C k23/array2d
	$(MAKE) -C k28
	$(MAKE) -C k28/iterator_traits
	$(MAKE) -C k28/bezeichnerlesen
	$(MAKE) -C k26/forward
	$(MAKE) -C k26
	$(MAKE) -C k26/tuple
	$(MAKE) -C k26/pair
	$(MAKE) -C k26/ratio
	$(MAKE) -C k26/type_traits
	$(MAKE) -C k26/bind
	$(MAKE) -C k26/funktionsobjekt
	$(MAKE) -C k4
	$(MAKE) -C k4/array2d
	$(MAKE) -C k10/einf
	$(MAKE) -C k10/liste
	$(MAKE) -C k31
	$(MAKE) -C k6
	$(MAKE) -C k6/abstrakt
	$(MAKE) -C k6/konstruktorerben
	$(MAKE) -C k6/privateVererbung
	$(MAKE) -C k6/privateVirtualFunctions
	$(MAKE) -C k6/mehrfach
	$(MAKE) -C k6/mehrfach/konflikt
	$(MAKE) -C k6/mehrfach/virtual
	$(MAKE) -C k6/erben
	$(MAKE) -C loesungen/k1
	$(MAKE) -C loesungen/k1/einausgabe
	$(MAKE) -C loesungen/k8/6_7
	$(MAKE) -C loesungen/k8/10_bis_13_15
	$(MAKE) -C loesungen/k8/1_bis_4
	$(MAKE) -C loesungen/k32/1
	$(MAKE) -C loesungen/k27
	$(MAKE) -C loesungen/k2
	$(MAKE) -C loesungen/k2/9
	$(MAKE) -C loesungen/k2/11
	$(MAKE) -C loesungen/k2/10
	$(MAKE) -C loesungen/k13
	$(MAKE) -C loesungen/k15/1
	$(MAKE) -C loesungen/k15/2
	$(MAKE) -C loesungen/k5/3/loesung2
	$(MAKE) -C loesungen/k5/3/loesung1
	$(MAKE) -C loesungen/k5/4
	$(MAKE) -C loesungen/k5/1
	$(MAKE) -C loesungen/k5/2
	$(MAKE) -C loesungen/k23/1
	$(MAKE) -C loesungen/k23/2
	$(MAKE) -C loesungen/k4
	$(MAKE) -C loesungen/k10
	$(MAKE) -C loesungen/k6/3
	$(MAKE) -C loesungen/k6/4_5
	$(MAKE) -C loesungen/k6/2
	$(MAKE) -C loesungen/k3
	$(MAKE) -C loesungen/k3/3
	$(MAKE) -C loesungen/k3/4
	$(MAKE) -C loesungen/k3/1
	$(MAKE) -C loesungen/k3/7
	$(MAKE) -C loesungen/k29
	$(MAKE) -C k3
	$(MAKE) -C k3/constexpr
	$(MAKE) -C k3/sequenzkonstruktor
	$(MAKE) -C k3/personalverwaltung
	$(MAKE) -C k3/kopierkonstruktor
	$(MAKE) -C k3/ort1
	$(MAKE) -C k3/delegierenderKonstruktor
	$(MAKE) -C k3/rational
	$(MAKE) -C k9
	$(MAKE) -C k9/binaer
	$(MAKE) -C k9/sstream
	$(MAKE) -C k9/tabelle
	$(MAKE) -C k9/datum
	$(MAKE) -C k30
	$(MAKE) -C k30/geld
	$(MAKE) -C k30/datum
	$(MAKE) -C k18
	$(MAKE) -C k17/host
	$(MAKE) -C k17/http/get
	$(MAKE) -C k17/http/server
	$(MAKE) -C k17/udpsocket
	$(MAKE) -C k17/tcpsocket/bidirectional
	$(MAKE) -C k17/tcpsocket/zeit
clean:
	$(MAKE) -C k1 clean
	$(MAKE) -C k1/einausgabe clean
	$(MAKE) -C k24 clean
	$(MAKE) -C k12 clean
	$(MAKE) -C k8/mathvek clean
	$(MAKE) -C k8/vektor clean
	$(MAKE) -C k8/matrix clean
	$(MAKE) -C k8/funktor clean
	$(MAKE) -C k8/zuweisung_vergleich clean
	$(MAKE) -C k8/literale clean
	$(MAKE) -C k8/new/waechter clean
	$(MAKE) -C k8/new/eigene clean
	$(MAKE) -C k8/new/zaehlend clean
	$(MAKE) -C k8/new/new clean
	$(MAKE) -C k8/smartptr clean
	$(MAKE) -C k8/datum clean
	$(MAKE) -C k8/rational clean
	$(MAKE) -C k7 clean
	$(MAKE) -C k7/logik clean
	$(MAKE) -C k7/speicher clean
	$(MAKE) -C k7/stream clean
	$(MAKE) -C k32 clean
	$(MAKE) -C k27 clean
	$(MAKE) -C k27/array clean
	$(MAKE) -C k27/vector clean
	$(MAKE) -C k27/list clean
	$(MAKE) -C k19 clean
	$(MAKE) -C k19/dynLib/anwendung clean
	$(MAKE) -C k19/dynLib/libprojekt clean
	$(MAKE) -C k19/abhaengigkeiten clean
	$(MAKE) -C k19/verzTrennung clean
	$(MAKE) -C k19/templateInst/inklusion clean
	$(MAKE) -C k19/templateInst/extern clean
	$(MAKE) -C k19/staticLib/anwendung clean
	$(MAKE) -C k19/staticLib/libprojekt clean
	$(MAKE) -C k19/dirTreeRec clean
	$(MAKE) -C k19/dirTree clean
	$(MAKE) -C k14 clean
	$(MAKE) -C k14/RegexTester clean
	$(MAKE) -C k11/tauschen clean
	$(MAKE) -C k11/plus clean
	$(MAKE) -C k11/RVO clean
	$(MAKE) -C k11/move clean
	$(MAKE) -C k11/move/unique_ptr clean
	$(MAKE) -C k2 clean
	$(MAKE) -C k2/inline clean
	$(MAKE) -C k20 clean
	$(MAKE) -C k20/tdd clean
	$(MAKE) -C k20/datum clean
	$(MAKE) -C k21 clean
	$(MAKE) -C k13/rekursiveTemplates clean
	$(MAKE) -C k13/variadicTemplate clean
	$(MAKE) -C k33 clean
	$(MAKE) -C k22/bidirektionaleAssoziation clean
	$(MAKE) -C k22/interface clean
	$(MAKE) -C k15 clean
	$(MAKE) -C k15/prodcons clean
	$(MAKE) -C k15/rw clean
	$(MAKE) -C k5/decltype clean
	$(MAKE) -C k5/klasseMitKonstanten clean
	$(MAKE) -C k5/meinstring clean
	$(MAKE) -C k5/numobj clean
	$(MAKE) -C k5/numobjinline clean
	$(MAKE) -C k5/stack clean
	$(MAKE) -C k5/stringansicht clean
	$(MAKE) -C k23/strings clean
	$(MAKE) -C k23/strings/zahl2string clean
	$(MAKE) -C k23/strings/string2zahl clean
	$(MAKE) -C k23/array2dmath clean
	$(MAKE) -C k23/array2dmath/performancetest clean
	$(MAKE) -C k23/array2dmath/performancetest/boost clean
	$(MAKE) -C k23/array2dmath/performancetest/array2d clean
	$(MAKE) -C k23/sortieren clean
	$(MAKE) -C k23/finden clean
	$(MAKE) -C k23/complex clean
	$(MAKE) -C k23/vermischtes clean
	$(MAKE) -C k23/vermischtes/regex clean
	$(MAKE) -C k23/vermischtes/copy clean
	$(MAKE) -C k23/zufallszahlen clean
	$(MAKE) -C k23/vergleich clean
	$(MAKE) -C k23/mengen clean
	$(MAKE) -C k23/textverarbeitung clean
	$(MAKE) -C k23/textverarbeitung/regex clean
	$(MAKE) -C k23/folgen clean
	$(MAKE) -C k23/heap clean
	$(MAKE) -C k23/array2d clean
	$(MAKE) -C k28 clean
	$(MAKE) -C k28/iterator_traits clean
	$(MAKE) -C k28/bezeichnerlesen clean
	$(MAKE) -C k26/forward clean
	$(MAKE) -C k26 clean
	$(MAKE) -C k26/tuple clean
	$(MAKE) -C k26/pair clean
	$(MAKE) -C k26/ratio clean
	$(MAKE) -C k26/type_traits clean
	$(MAKE) -C k26/bind clean
	$(MAKE) -C k26/funktionsobjekt clean
	$(MAKE) -C k4 clean
	$(MAKE) -C k4/array2d clean
	$(MAKE) -C k10/einf clean
	$(MAKE) -C k10/liste clean
	$(MAKE) -C k31 clean
	$(MAKE) -C k6 clean
	$(MAKE) -C k6/abstrakt clean
	$(MAKE) -C k6/konstruktorerben clean
	$(MAKE) -C k6/privateVererbung clean
	$(MAKE) -C k6/privateVirtualFunctions clean
	$(MAKE) -C k6/mehrfach clean
	$(MAKE) -C k6/mehrfach/konflikt clean
	$(MAKE) -C k6/mehrfach/virtual clean
	$(MAKE) -C k6/erben clean
	$(MAKE) -C loesungen/k1 clean
	$(MAKE) -C loesungen/k1/einausgabe clean
	$(MAKE) -C loesungen/k8/6_7 clean
	$(MAKE) -C loesungen/k8/10_bis_13_15 clean
	$(MAKE) -C loesungen/k8/1_bis_4 clean
	$(MAKE) -C loesungen/k32/1 clean
	$(MAKE) -C loesungen/k27 clean
	$(MAKE) -C loesungen/k2 clean
	$(MAKE) -C loesungen/k2/9 clean
	$(MAKE) -C loesungen/k2/11 clean
	$(MAKE) -C loesungen/k2/10 clean
	$(MAKE) -C loesungen/k13 clean
	$(MAKE) -C loesungen/k15/1 clean
	$(MAKE) -C loesungen/k15/2 clean
	$(MAKE) -C loesungen/k5/3/loesung2 clean
	$(MAKE) -C loesungen/k5/3/loesung1 clean
	$(MAKE) -C loesungen/k5/4 clean
	$(MAKE) -C loesungen/k5/1 clean
	$(MAKE) -C loesungen/k5/2 clean
	$(MAKE) -C loesungen/k23/1 clean
	$(MAKE) -C loesungen/k23/2 clean
	$(MAKE) -C loesungen/k4 clean
	$(MAKE) -C loesungen/k10 clean
	$(MAKE) -C loesungen/k6/3 clean
	$(MAKE) -C loesungen/k6/4_5 clean
	$(MAKE) -C loesungen/k6/2 clean
	$(MAKE) -C loesungen/k3 clean
	$(MAKE) -C loesungen/k3/3 clean
	$(MAKE) -C loesungen/k3/4 clean
	$(MAKE) -C loesungen/k3/1 clean
	$(MAKE) -C loesungen/k3/7 clean
	$(MAKE) -C loesungen/k29 clean
	$(MAKE) -C k3 clean
	$(MAKE) -C k3/constexpr clean
	$(MAKE) -C k3/sequenzkonstruktor clean
	$(MAKE) -C k3/personalverwaltung clean
	$(MAKE) -C k3/kopierkonstruktor clean
	$(MAKE) -C k3/ort1 clean
	$(MAKE) -C k3/delegierenderKonstruktor clean
	$(MAKE) -C k3/rational clean
	$(MAKE) -C k9 clean
	$(MAKE) -C k9/binaer clean
	$(MAKE) -C k9/sstream clean
	$(MAKE) -C k9/tabelle clean
	$(MAKE) -C k9/datum clean
	$(MAKE) -C k30 clean
	$(MAKE) -C k30/geld clean
	$(MAKE) -C k30/datum clean
	$(MAKE) -C k18 clean
	$(MAKE) -C k17/host clean
	$(MAKE) -C k17/http/get clean
	$(MAKE) -C k17/http/server clean
	$(MAKE) -C k17/udpsocket clean
	$(MAKE) -C k17/tcpsocket/bidirectional clean
	$(MAKE) -C k17/tcpsocket/zeit clean
