######################################################################
# Automatically generated by qmake (3.0) Sa Jul 16 12:06:19 2016
######################################################################

TEMPLATE = app
TARGET = window
INCLUDEPATH += .

# Input
HEADERS += Window.h
SOURCES += main.cpp

QT += widgets
