######################################################################
# Automatically generated by qmake (3.0) Sa Jul 16 12:12:43 2016
######################################################################

TEMPLATE = app
TARGET = signalslot
INCLUDEPATH += .

# Input
HEADERS += QtBeispiel.h Window.h Zeichenflaeche.h
SOURCES += main.cpp
QT += widgets
