######################################################################
# Automatically generated by qmake (3.0) Sa Jul 16 12:10:20 2016
######################################################################

TEMPLATE = app
TARGET = dialog
INCLUDEPATH += .

# Input
HEADERS += DialogUser.h NamenDialog.h
SOURCES += main.cpp
QT += widgets
