######################################################################
# Automatically generated by qmake (3.0) Sa Jul 16 12:08:37 2016
######################################################################

TEMPLATE = app
TARGET = dirtree
INCLUDEPATH += .

# Input
HEADERS += tree.h
SOURCES += main.cpp tree.cpp
CONFIG += console
