######################################################################
# Automatically generated by qmake (3.0) Sa. Juli 16 13:28:55 2016
######################################################################

TEMPLATE = app
TARGET = label
INCLUDEPATH += .

# Input
SOURCES += main.cpp

QT += widgets

CONFIG += console
